# Storage Class is not replicated, not regional
# Volumes that were dynamically provisioned inherit the reclaim policy of their StorageClass, 
# which defaults to Delete (meaning it will delete the PV)

# ref. https://kubernetes.io/docs/concepts/storage/storage-classes/#aws-ebs

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: news-postgres-storageclass
provisioner: kubernetes.io/aws-ebs
parameters:
  type: io1
  iopsPerGB: "10"
  fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: news-postgres-pvc
spec:
  storageClassName: news-postgres-storageclass
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi



  
