# Storage Class is not replicated, not regional
# Volumes that were dynamically provisioned inherit the reclaim policy of their StorageClass, 
# which defaults to Delete (meaning it will delete the PV)

# ref. https://kubernetes.io/docs/concepts/storage/storage-classes/#gce-pd

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: news-postgres-storageclass
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  fstype: ext4 
  replication-type: none 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: news-postgres-pvc
spec:
  storageClassName: news-postgres-storageclass
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi



  
