version: "3.9"
services:
  visualizer:
    build: ./visualizer
    networks:
      - localnet
    ports:
      - "8080:8080"
    depends_on:
      - db
  ncollector: 
    build: ./ncollector
    networks:
      - localnet
    depends_on:
      - db
  db:
    build: ./db
    networks:
      - localnet
    ports: 
      - "5432:5432" 
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  localnet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.1.0/24

volumes:
  pgdata: