services:
  ncollector: 
    build: ./ncollector
    #command: sh -c './wait-for db:5432 -- echo "DB Ready"'
    depends_on:
      - db
  db:
    build: ./db
    ports: 
      - "5432:5432" 


networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.1.0/24